PROVINCES = [
    "Pinar del Río",
    "Artemisa",
    "La Habana",
    "Mayabeque",
    "Matanzas",
    "Cienfuegos",
    "Villa Clara",
    "Sancti Spíritus",
    "Ciego de Ávila",
    "Camagüey",
    "Las Tunas",
    "Holguín",
    "Granma",
    "Santiago de Cuba",
    "Guantánamo",
    "Isla de la Juventud",
]

PROVINCE_RADAR_GEOIDS = {
    "Pinar del Río": 3544088,
    "Artemisa": 7668824,
    "La Habana": 3564073,
    "Mayabeque": 7668827,
    "Matanzas": 3547394,
    "Cienfuegos": 3564120,
    "Villa Clara": 3534168,
    "Sancti Spíritus": 3540665,
    "Ciego de Ávila": 3564175,
    "Camagüey": 3566062,
    "Las Tunas": 3550595,
    "Holguín": 3556965,
    "Granma": 3558052,
    "Santiago de Cuba": 3536725,
    "Guantánamo": 3557685,
    "Isla de la Juventud": 3556608,
}

MUNICIPALITIES = {
    "Pinar del Río": [
        "Pinar del Río",
        "Consolación del Sur",
        "Guane",
        "La Palma",
        "Los Palacios",
        "Mantua",
        "Minas de Matahambre",
        "San Juan y Martínez",
        "San Luis",
        "Sandino",
        "Viñales",
    ],
    "Artemisa": [
        "Alquízar",
        "Artemisa",
        "Bauta",
        "Caimito",
        "Guanajay",
        "Güira de Melena",
        "Mariel",
        "San Antonio de los Baños",
        "Bahía Honda",
        "Candelaria",
        "San Cristóbal",
    ],
    "La Habana": [
        "Playa",
        "Plaza de la Revolución",
        "Centro Habana",
        "La Habana Vieja",
        "Regla",
        "Habana del Este",
        "Guanabacoa",
        "San Miguel del Padrón",
        "Diez de Octubre",
        "Cerro",
        "Marianao",
        "La Lisa",
        "Boyeros",
        "Arroyo Naranjo",
        "Cotorro",
    ],
    "Mayabeque": [
        "Bejucal",
        "Jaruco",
        "Santa Cruz del Norte",
        "Madruga",
        "Nueva Paz",
        "San José de las Lajas",
        "Güines",
        "Melena del Sur",
        "Batabanó",
        "Quivicán",
        "San Nicolás",
    ],
    "Matanzas": [
        "Matanzas",
        "Cárdenas",
        "Martí",
        "Colón",
        "Perico",
        "Jovellanos",
        "Pedro Betancourt",
        "Limonar",
        "Unión de Reyes",
        "Ciénaga de Zapata",
        "Jagüey Grande",
        "Calimete",
        "Los Arabos",
    ],
    "Cienfuegos": [
        "Cienfuegos",
        "Aguada de Pasajeros",
        "Rodas",
        "Palmira",
        "Lajas",
        "Cruces",
        "Cumanayagua",
        "Abreus",
    ],
    "Villa Clara": [
        "Caibarién",
        "Camajuaní",
        "Cifuentes",
        "Corralillo",
        "Encrucijada",
        "Manicaragua",
        "Placetas",
        "Quemado de Güines",
        "Ranchuelo",
        "Remedios",
        "Sagua la Grande",
        "Santa Clara",
        "Santo Domingo",
    ],
    "Sancti Spíritus": [
        "Sancti Spíritus",
        "Cabaiguán",
        "Fomento",
        "Jatibonico",
        "La Sierpe",
        "Taguasco",
        "Trinidad",
        "Yaguajay",
    ],
    "Ciego de Ávila": [
        "Ciego de Ávila",
        "Baraguá",
        "Bolivia",
        "Chambas",
        "Ciro Redondo",
        "Florencia",
        "Majagua",
        "Morón",
        "Primero de Enero",
        "Venezuela",
    ],
    "Camagüey": [
        "Camagüey",
        "Carlos Manuel de Céspedes",
        "Esmeralda",
        "Florida",
        "Guáimaro",
        "Jimaguayú",
        "Minas",
        "Najasa",
        "Nuevitas",
        "Santa Cruz del Sur",
        "Sierra de Cubitas",
        "Sibanicú",
        "Vertientes",
    ],
    "Las Tunas": [
        "Las Tunas",
        "Amancio",
        "Colombia",
        "Jesús Menéndez",
        "Jobabo",
        "Manatí",
        "Majibacoa",
        "Puerto Padre",
    ],
    "Holguín": [
        "Holguín",
        "Antilla",
        "Báguanos",
        "Banes",
        "Cacocum",
        "Calixto García",
        "Cueto",
        "Frank País",
        "Gibara",
        "Mayarí",
        "Moa",
        "Rafael Freyre",
        "Sagua de Tánamo",
        "Urbano Noris",
    ],
    "Granma": [
        "Bayamo",
        "Buey Arriba",
        "Campechuela",
        "Cauto Cristo",
        "Guisa",
        "Jiguaní",
        "Manzanillo",
        "Media Luna",
        "Niquero",
        "Pilón",
        "Río Cauto",
        "Bartolomé Masó",
        "Yara",
    ],
    "Santiago de Cuba": [
        "Santiago de Cuba",
        "Contramaestre",
        "Guamá",
        "Mella",
        "Palma Soriano",
        "San Luis",
        "Segundo Frente",
        "Songo-La Maya",
        "Tercer Frente",
    ],
    "Guantánamo": [
        "Guantánamo",
        "Baracoa",
        "Caimanera",
        "El Salvador",
        "Imías",
        "Maisí",
        "Manuel Tames",
        "Niceto Pérez",
        "San Antonio del Sur",
        "Yateras",
    ],
    "Isla de la Juventud": [
        "Isla de la Juventud",
    ],
}
