import os


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY", "dev-change-me")
    SQLALCHEMY_DATABASE_URI = os.getenv(
        "DATABASE_URL",
        "postgresql+psycopg://postgres:postgres@localhost:5432/soscubamap",
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SESSION_COOKIE_SECURE = False
    REMEMBER_COOKIE_SECURE = False
    WTF_CSRF_ENABLED = True
    APP_NAME = "#SOSCuba Map"
    DEFAULT_LANGUAGE = "es"
    BABEL_DEFAULT_LOCALE = "es"
    BABEL_TRANSLATION_DIRECTORIES = "../translations"
    GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
    GOOGLE_MAPS_MAP_ID = os.getenv("GOOGLE_MAPS_MAP_ID", "")
    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "")
    IMAGE_MAX_MB = int(os.getenv("IMAGE_MAX_MB", "2"))
    IMAGE_MAX_PER_SUBMIT = int(os.getenv("IMAGE_MAX_PER_SUBMIT", "3"))
    IMAGE_ALLOWED_EXTENSIONS = os.getenv(
        "IMAGE_ALLOWED_EXTENSIONS",
        "jpg,jpeg,png,webp,heic",
    )
    GEOJSON_PROVINCES_PATH = os.getenv("GEOJSON_PROVINCES_PATH", "")
    GEOJSON_MUNICIPALITIES_PATH = os.getenv("GEOJSON_MUNICIPALITIES_PATH", "")
    GEOJSON_LOCALITIES_PATH = os.getenv("GEOJSON_LOCALITIES_PATH", "")
    GEOJSON_PROVINCE_KEYS = os.getenv("GEOJSON_PROVINCE_KEYS", "")
    GEOJSON_MUNICIPALITY_KEYS = os.getenv("GEOJSON_MUNICIPALITY_KEYS", "")
    GEOJSON_MUNICIPALITY_PROVINCE_KEYS = os.getenv(
        "GEOJSON_MUNICIPALITY_PROVINCE_KEYS", ""
    )
    GEOJSON_LOCALITY_KEYS = os.getenv("GEOJSON_LOCALITY_KEYS", "")
    GEOJSON_LOCALITY_MUNICIPALITY_KEYS = os.getenv(
        "GEOJSON_LOCALITY_MUNICIPALITY_KEYS", ""
    )
    GEOJSON_LOCALITY_PROVINCE_KEYS = os.getenv("GEOJSON_LOCALITY_PROVINCE_KEYS", "")
    POSTS_REQUIRE_MODERATION = True
    ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@soscuba.local")
    ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
    RATELIMIT_STORAGE_URL = os.getenv("RATELIMIT_STORAGE_URL", "memory://")
    RATELIMIT_HEADERS_ENABLED = True
    TRUST_PROXY_HEADERS = os.getenv("TRUST_PROXY_HEADERS", "1") == "1"
    RECAPTCHA_V2_SITE_KEY = os.getenv("RECAPTCHA_V2_SITE_KEY", "")
    RECAPTCHA_V2_SECRET_KEY = os.getenv("RECAPTCHA_V2_SECRET_KEY", "")
    CHAT_DISABLED = os.getenv("CHAT_DISABLED", "0") == "1"
    ASSET_VERSION = os.getenv("ASSET_VERSION", "1")
    VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
    VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
    VAPID_SUBJECT = os.getenv("VAPID_SUBJECT", "mailto:soscubamap@proton.me")
    CLOUDFLARE_RADAR_HTTP_TIMESERIES_URL = os.getenv(
        "CLOUDFLARE_RADAR_HTTP_TIMESERIES_URL",
        "https://api.cloudflare.com/client/v4/radar/http/timeseries?name=main&name=previous&geoId=3556965&geoId=3556965&dateRange=1d&dateRange=1dControl",
    )
    CONNECTIVITY_FETCH_DELAY_SECONDS = int(
        os.getenv("CONNECTIVITY_FETCH_DELAY_SECONDS", "120")
    )
    CONNECTIVITY_FETCH_TIMEOUT_SECONDS = int(
        os.getenv("CONNECTIVITY_FETCH_TIMEOUT_SECONDS", "30")
    )
    CONNECTIVITY_STALE_AFTER_HOURS = int(
        os.getenv("CONNECTIVITY_STALE_AFTER_HOURS", "8")
    )
    CONNECTIVITY_FRONTEND_REFRESH_SECONDS = int(
        os.getenv("CONNECTIVITY_FRONTEND_REFRESH_SECONDS", "300")
    )
    PROTEST_RSS_FEEDS = os.getenv("PROTEST_RSS_FEEDS", "")
    PROTEST_FETCH_TIMEOUT_SECONDS = int(
        os.getenv("PROTEST_FETCH_TIMEOUT_SECONDS", "30")
    )
    PROTEST_FRONTEND_REFRESH_SECONDS = int(
        os.getenv("PROTEST_FRONTEND_REFRESH_SECONDS", "300")
    )
    PROTEST_MIN_CONFIDENCE_TO_SHOW = float(
        os.getenv("PROTEST_MIN_CONFIDENCE_TO_SHOW", "35")
    )
    PROTEST_REQUIRE_SOURCE_URL = os.getenv("PROTEST_REQUIRE_SOURCE_URL", "1") == "1"
    PROTEST_ALLOW_UNRESOLVED_TO_MAP = (
        os.getenv("PROTEST_ALLOW_UNRESOLVED_TO_MAP", "0") == "1"
    )
    PROTEST_MAX_ITEMS_PER_FEED = int(os.getenv("PROTEST_MAX_ITEMS_PER_FEED", "120"))
    PROTEST_MAX_POST_AGE_DAYS = int(os.getenv("PROTEST_MAX_POST_AGE_DAYS", "30"))
    PROTEST_KEYWORDS_STRONG = os.getenv("PROTEST_KEYWORDS_STRONG", "")
    PROTEST_KEYWORDS_CONTEXT = os.getenv("PROTEST_KEYWORDS_CONTEXT", "")
    PROTEST_KEYWORDS_WEAK = os.getenv("PROTEST_KEYWORDS_WEAK", "")
    PROTEST_PLACE_ALIASES_JSON = os.getenv("PROTEST_PLACE_ALIASES_JSON", "")
