import os


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY", "dev-change-me")
    SQLALCHEMY_DATABASE_URI = os.getenv(
        "DATABASE_URL",
        "postgresql+psycopg://postgres:postgres@localhost:5432/soscubamap",
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SESSION_COOKIE_SECURE = False
    REMEMBER_COOKIE_SECURE = False
    WTF_CSRF_ENABLED = True
    APP_NAME = "#SOSCuba Map"
    DEFAULT_LANGUAGE = "es"
    GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
    GOOGLE_MAPS_MAP_ID = os.getenv("GOOGLE_MAPS_MAP_ID", "")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
    OPENAI_TEXT_MODEL = os.getenv("OPENAI_TEXT_MODEL", "gpt-4o-mini")
    OPENAI_TIMEOUT_SECONDS = int(os.getenv("OPENAI_TIMEOUT_SECONDS", "30"))
    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "")
    IMAGE_MAX_MB = int(os.getenv("IMAGE_MAX_MB", "2"))
    IMAGE_MAX_PER_SUBMIT = int(os.getenv("IMAGE_MAX_PER_SUBMIT", "3"))
    IMAGE_ALLOWED_EXTENSIONS = os.getenv(
        "IMAGE_ALLOWED_EXTENSIONS",
        "jpg,jpeg,png,webp,heic",
    )
    GEOJSON_PROVINCES_PATH = os.getenv("GEOJSON_PROVINCES_PATH", "")
    GEOJSON_MUNICIPALITIES_PATH = os.getenv("GEOJSON_MUNICIPALITIES_PATH", "")
    GEOJSON_LOCALITIES_PATH = os.getenv("GEOJSON_LOCALITIES_PATH", "")
    GEOJSON_PROVINCE_KEYS = os.getenv("GEOJSON_PROVINCE_KEYS", "")
    GEOJSON_MUNICIPALITY_KEYS = os.getenv("GEOJSON_MUNICIPALITY_KEYS", "")
    GEOJSON_MUNICIPALITY_PROVINCE_KEYS = os.getenv("GEOJSON_MUNICIPALITY_PROVINCE_KEYS", "")
    GEOJSON_LOCALITY_KEYS = os.getenv("GEOJSON_LOCALITY_KEYS", "")
    GEOJSON_LOCALITY_MUNICIPALITY_KEYS = os.getenv("GEOJSON_LOCALITY_MUNICIPALITY_KEYS", "")
    GEOJSON_LOCALITY_PROVINCE_KEYS = os.getenv("GEOJSON_LOCALITY_PROVINCE_KEYS", "")
    POSTS_REQUIRE_MODERATION = True
    ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@soscuba.local")
    ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
    RATELIMIT_STORAGE_URI = os.getenv(
        "RATELIMIT_STORAGE_URI",
        os.getenv("RATELIMIT_STORAGE_URL", "memory://"),
    )
    RATELIMIT_HEADERS_ENABLED = True
    TRUST_PROXY_HEADERS = os.getenv("TRUST_PROXY_HEADERS", "1") == "1"
    RECAPTCHA_V2_SITE_KEY = os.getenv("RECAPTCHA_V2_SITE_KEY", "")
    RECAPTCHA_V2_SECRET_KEY = os.getenv("RECAPTCHA_V2_SECRET_KEY", "")
    CHAT_DISABLED = os.getenv("CHAT_DISABLED", "0") == "1"
    ASSET_VERSION = os.getenv("ASSET_VERSION", "1")
    VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
    VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
    VAPID_SUBJECT = os.getenv("VAPID_SUBJECT", "mailto:soscubamap@proton.me")
    CLOUDFLARE_RADAR_HTTP_TIMESERIES_URL = os.getenv(
        "CLOUDFLARE_RADAR_HTTP_TIMESERIES_URL",
        "https://api.cloudflare.com/client/v4/radar/http/timeseries?name=main&name=previous&geoId=3556965&geoId=3556965&dateRange=1d&dateRange=1dControl",
    )
    CLOUDFLARE_RADAR_API_BASE_URL = os.getenv(
        "CLOUDFLARE_RADAR_API_BASE_URL",
        "https://api.cloudflare.com/client/v4/radar",
    )
    CONNECTIVITY_FETCH_DELAY_SECONDS = int(os.getenv("CONNECTIVITY_FETCH_DELAY_SECONDS", "120"))
    CONNECTIVITY_FETCH_TIMEOUT_SECONDS = int(os.getenv("CONNECTIVITY_FETCH_TIMEOUT_SECONDS", "30"))
    CONNECTIVITY_ALERT_ACTIVE_MAX_AGE_HOURS = int(
        os.getenv("CONNECTIVITY_ALERT_ACTIVE_MAX_AGE_HOURS", "24")
    )
    CONNECTIVITY_STALE_AFTER_HOURS = int(os.getenv("CONNECTIVITY_STALE_AFTER_HOURS", "8"))
    CONNECTIVITY_FRONTEND_REFRESH_SECONDS = int(
        os.getenv("CONNECTIVITY_FRONTEND_REFRESH_SECONDS", "300")
    )
    CONNECTIVITY_RADAR_ENRICHMENT_COOLDOWN_SECONDS = int(
        os.getenv("CONNECTIVITY_RADAR_ENRICHMENT_COOLDOWN_SECONDS", "21600")
    )
    AISSTREAM_ENABLED = os.getenv("AISSTREAM_ENABLED", "0") == "1"
    AISSTREAM_API_KEY = os.getenv("AISSTREAM_API_KEY", "")
    AISSTREAM_WS_URL = os.getenv("AISSTREAM_WS_URL", "wss://stream.aisstream.io/v0/stream")
    AISSTREAM_SUBSCRIPTION_BBOXES_JSON = os.getenv(
        "AISSTREAM_SUBSCRIPTION_BBOXES_JSON",
        "[[[17.5, -88.5], [25.8, -73.0]]]",
    )
    AISSTREAM_CAPTURE_MINUTES = int(os.getenv("AISSTREAM_CAPTURE_MINUTES", "30"))
    AISSTREAM_MAX_MESSAGES_PER_RUN = int(os.getenv("AISSTREAM_MAX_MESSAGES_PER_RUN", "120000"))
    AISSTREAM_INGESTION_INTERVAL_SECONDS = int(
        os.getenv("AISSTREAM_INGESTION_INTERVAL_SECONDS", "86400")
    )
    AISSTREAM_FRONTEND_REFRESH_SECONDS = int(
        os.getenv("AISSTREAM_FRONTEND_REFRESH_SECONDS", "1800")
    )
    AISSTREAM_STALE_AFTER_HOURS = int(os.getenv("AISSTREAM_STALE_AFTER_HOURS", "48"))
    AISSTREAM_VESSEL_STALE_HOURS = int(os.getenv("AISSTREAM_VESSEL_STALE_HOURS", "168"))
    AISSTREAM_MAX_TARGET_VESSELS = int(os.getenv("AISSTREAM_MAX_TARGET_VESSELS", "1500"))
    AISSTREAM_MIN_SOG_FOR_DIRECTION_KNOTS = float(
        os.getenv("AISSTREAM_MIN_SOG_FOR_DIRECTION_KNOTS", "1.0")
    )
    AISSTREAM_MAX_DIRECTION_DELTA_DEG = float(
        os.getenv("AISSTREAM_MAX_DIRECTION_DELTA_DEG", "70")
    )
    AISSTREAM_MAX_DIRECTION_DISTANCE_NM = float(
        os.getenv("AISSTREAM_MAX_DIRECTION_DISTANCE_NM", "1200")
    )
    FLIGHTS_ENABLED = os.getenv("FLIGHTS_ENABLED", "0") == "1"
    FLIGHTS_API_KEY = os.getenv("FLIGHTS_API_KEY", "")
    FLIGHTS_API_BASE_URL = os.getenv(
        "FLIGHTS_API_BASE_URL", "https://fr24api.flightradar24.com/api"
    )
    FLIGHTS_API_AUTH_HEADER = os.getenv("FLIGHTS_API_AUTH_HEADER", "Authorization")
    FLIGHTS_API_AUTH_PREFIX = os.getenv("FLIGHTS_API_AUTH_PREFIX", "Bearer")
    FLIGHTS_API_ACCEPT_VERSION = os.getenv("FLIGHTS_API_ACCEPT_VERSION", "v1")
    FLIGHTS_API_TIMEOUT_SECONDS = int(os.getenv("FLIGHTS_API_TIMEOUT_SECONDS", "20"))
    FLIGHTS_API_RESPONSE_LIMIT = int(os.getenv("FLIGHTS_API_RESPONSE_LIMIT", "20"))
    FLIGHTS_API_REQUEST_RATE_LIMIT = int(os.getenv("FLIGHTS_API_REQUEST_RATE_LIMIT", "10"))
    FLIGHTS_API_MAX_RETRIES = int(os.getenv("FLIGHTS_API_MAX_RETRIES", "2"))
    FLIGHTS_API_RETRY_BACKOFF_SECONDS = float(
        os.getenv("FLIGHTS_API_RETRY_BACKOFF_SECONDS", "1.5")
    )
    FLIGHTS_INGESTION_INTERVAL_SECONDS = int(
        os.getenv("FLIGHTS_INGESTION_INTERVAL_SECONDS", "900")
    )
    FLIGHTS_FRONTEND_REFRESH_SECONDS = int(
        os.getenv("FLIGHTS_FRONTEND_REFRESH_SECONDS", "300")
    )
    FLIGHTS_STALE_AFTER_SECONDS = int(os.getenv("FLIGHTS_STALE_AFTER_SECONDS", "1800"))
    FLIGHTS_REQUEST_CAP_PER_RUN = int(os.getenv("FLIGHTS_REQUEST_CAP_PER_RUN", "120"))
    FLIGHTS_SAFE_REQUEST_CAP_PER_RUN = int(
        os.getenv("FLIGHTS_SAFE_REQUEST_CAP_PER_RUN", "40")
    )
    FLIGHTS_MONTHLY_CREDIT_BUDGET = int(os.getenv("FLIGHTS_MONTHLY_CREDIT_BUDGET", "60000"))
    FLIGHTS_GUARDRAIL_PERCENT = float(os.getenv("FLIGHTS_GUARDRAIL_PERCENT", "85"))
    FLIGHTS_ESTIMATED_CREDIT_PER_REQUEST = int(
        os.getenv("FLIGHTS_ESTIMATED_CREDIT_PER_REQUEST", "1")
    )
    FLIGHTS_BACKFILL_DAYS = int(os.getenv("FLIGHTS_BACKFILL_DAYS", "7"))
    FLIGHTS_BACKFILL_CHUNK_HOURS = int(os.getenv("FLIGHTS_BACKFILL_CHUNK_HOURS", "24"))
    FLIGHTS_POLLING_HISTORIC_HOURS = int(os.getenv("FLIGHTS_POLLING_HISTORIC_HOURS", "24"))
    FLIGHTS_BACKFILL_ON_EMPTY_DB = os.getenv("FLIGHTS_BACKFILL_ON_EMPTY_DB", "0") == "1"
    FLIGHTS_BACKFILL_HISTORIC_ENABLED = (
        os.getenv("FLIGHTS_BACKFILL_HISTORIC_ENABLED", "0") == "1"
    )
    FLIGHTS_SAFE_MODE_SKIP_BACKFILL = (
        os.getenv("FLIGHTS_SAFE_MODE_SKIP_BACKFILL", "1") == "1"
    )
    FLIGHTS_AIRPORTS_SYNC_ENABLED = os.getenv("FLIGHTS_AIRPORTS_SYNC_ENABLED", "0") == "1"
    FLIGHTS_AIRPORTS_SYNC_INTERVAL_SECONDS = int(
        os.getenv("FLIGHTS_AIRPORTS_SYNC_INTERVAL_SECONDS", "86400")
    )
    FLIGHTS_AIRPORTS_MAX_PAGES = int(os.getenv("FLIGHTS_AIRPORTS_MAX_PAGES", "10"))
    FLIGHTS_EVENTS_MAX_PAGES = int(os.getenv("FLIGHTS_EVENTS_MAX_PAGES", "5"))
    FLIGHTS_SAFE_EVENTS_MAX_PAGES = int(os.getenv("FLIGHTS_SAFE_EVENTS_MAX_PAGES", "2"))
    FLIGHTS_LAYER_MAX_POINTS = int(os.getenv("FLIGHTS_LAYER_MAX_POINTS", "2000"))
    FLIGHTS_TRACK_POINT_LIMIT = int(os.getenv("FLIGHTS_TRACK_POINT_LIMIT", "2000"))
    FLIGHTS_API_AIRPORTS_LIGHT_PATH = os.getenv(
        "FLIGHTS_API_AIRPORTS_LIGHT_PATH", "/static/airports/{code}/light"
    )
    FLIGHTS_API_LIVE_POSITIONS_LIGHT_PATH = os.getenv(
        "FLIGHTS_API_LIVE_POSITIONS_LIGHT_PATH", "/live/flight-positions/light"
    )
    FLIGHTS_API_HISTORIC_EVENTS_LIGHT_PATH = os.getenv(
        "FLIGHTS_API_HISTORIC_EVENTS_LIGHT_PATH", "/historic/flight-events/light"
    )
    FLIGHTS_API_HISTORIC_POSITIONS_LIGHT_PATH = os.getenv(
        "FLIGHTS_API_HISTORIC_POSITIONS_LIGHT_PATH", "/historic/flight-positions/light"
    )
    FLIGHTS_API_TRACKS_PATH = os.getenv("FLIGHTS_API_TRACKS_PATH", "/flights/tracks")
    FLIGHTS_LIVE_FILTER_BOUNDS = os.getenv("FLIGHTS_LIVE_FILTER_BOUNDS", "")
    FLIGHTS_LIVE_FILTER_AIRPORTS = os.getenv("FLIGHTS_LIVE_FILTER_AIRPORTS", "inbound:CU")
    FLIGHTS_CUBA_AIRPORT_CODES = os.getenv(
        "FLIGHTS_CUBA_AIRPORT_CODES",
        "MUHA,HAV,MUCU,SCU,MUVR,VRA,MUCC,CCC,MUCM,CMW,MUSC,SNU,MUBY,BCA,MUGT,BWW,MUMZ,MZG,MUCL,CYO,MUBA",
    )
    PROTEST_RSS_FEEDS_JSON_PATH = os.getenv(
        "PROTEST_RSS_FEEDS_JSON_PATH",
        "app/static/data/protest_feeds.json",
    )
    PROTEST_FETCH_TIMEOUT_SECONDS = int(os.getenv("PROTEST_FETCH_TIMEOUT_SECONDS", "20"))
    PROTEST_FETCH_INTERVAL_SECONDS = int(os.getenv("PROTEST_FETCH_INTERVAL_SECONDS", "300"))
    PROTEST_FRONTEND_REFRESH_SECONDS = int(os.getenv("PROTEST_FRONTEND_REFRESH_SECONDS", "300"))
    PROTEST_MIN_CONFIDENCE_TO_SHOW = float(os.getenv("PROTEST_MIN_CONFIDENCE_TO_SHOW", "10"))
    PROTEST_REQUIRE_SOURCE_URL = os.getenv("PROTEST_REQUIRE_SOURCE_URL", "1") == "1"
    PROTEST_ALLOW_UNRESOLVED_TO_MAP = os.getenv("PROTEST_ALLOW_UNRESOLVED_TO_MAP", "0") == "1"
    PROTEST_MAX_ITEMS_PER_FEED = int(os.getenv("PROTEST_MAX_ITEMS_PER_FEED", "120"))
    PROTEST_MAX_POST_AGE_DAYS = int(os.getenv("PROTEST_MAX_POST_AGE_DAYS", "7"))
    PROTEST_KEYWORDS_STRONG = os.getenv("PROTEST_KEYWORDS_STRONG", "")
    PROTEST_KEYWORDS_CONTEXT = os.getenv("PROTEST_KEYWORDS_CONTEXT", "")
    PROTEST_KEYWORDS_WEAK = os.getenv("PROTEST_KEYWORDS_WEAK", "")
    PROTEST_PLACE_ALIASES_JSON = os.getenv("PROTEST_PLACE_ALIASES_JSON", "")
    PROTEST_SOURCE_NAME_OVERRIDES_JSON = os.getenv("PROTEST_SOURCE_NAME_OVERRIDES_JSON", "")
    REPRESSOR_API_BASE_URL = os.getenv(
        "REPRESSOR_API_BASE_URL", "https://data.represorescubanos.com"
    )
    REPRESSOR_PUBLIC_BASE_URL = os.getenv(
        "REPRESSOR_PUBLIC_BASE_URL", "https://represorescubanos.com/repressor-detail"
    )
    REPRESSOR_FETCH_TIMEOUT_SECONDS = float(
        os.getenv("REPRESSOR_FETCH_TIMEOUT_SECONDS", "20")
    )
    REPRESSOR_FETCH_RETRIES = int(os.getenv("REPRESSOR_FETCH_RETRIES", "3"))
    REPRESSOR_FETCH_PAUSE_SECONDS = float(
        os.getenv("REPRESSOR_FETCH_PAUSE_SECONDS", "0")
    )
    REPRESSOR_SCAN_START_ID = int(os.getenv("REPRESSOR_SCAN_START_ID", "1"))
    REPRESSOR_INGESTION_INTERVAL_SECONDS = int(
        os.getenv("REPRESSOR_INGESTION_INTERVAL_SECONDS", "86400")
    )
    REPRESSOR_BACKUP_JSON_PATH = os.getenv(
        "REPRESSOR_BACKUP_JSON_PATH", "data/repressors_backup_latest.json"
    )
    REPRESSOR_RESIDENCE_AUTO_APPROVE = (
        os.getenv("REPRESSOR_RESIDENCE_AUTO_APPROVE", "0") == "1"
    )
    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/1")
    CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
    CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", "UTC")
    CELERY_PROTEST_INGESTION_ENABLED = os.getenv("CELERY_PROTEST_INGESTION_ENABLED", "1") == "1"
    CELERY_PROTEST_QUEUE = os.getenv("CELERY_PROTEST_QUEUE", "ingestion")
    CELERY_CONNECTIVITY_POLLING_ENABLED = (
        os.getenv("CELERY_CONNECTIVITY_POLLING_ENABLED", "1") == "1"
    )
    CELERY_CONNECTIVITY_POLLING_INTERVAL_SECONDS = int(
        os.getenv("CELERY_CONNECTIVITY_POLLING_INTERVAL_SECONDS", "7200")
    )
    CELERY_CONNECTIVITY_SINGLE_CALL = os.getenv("CELERY_CONNECTIVITY_SINGLE_CALL", "1") == "1"
    CELERY_CONNECTIVITY_QUEUE = os.getenv("CELERY_CONNECTIVITY_QUEUE", "ingestion")
    CELERY_AIS_INGESTION_ENABLED = os.getenv("CELERY_AIS_INGESTION_ENABLED", "1") == "1"
    CELERY_AIS_QUEUE = os.getenv("CELERY_AIS_QUEUE", "ingestion")
    CELERY_FLIGHTS_INGESTION_ENABLED = (
        os.getenv("CELERY_FLIGHTS_INGESTION_ENABLED", "1") == "1"
    )
    CELERY_FLIGHTS_QUEUE = os.getenv("CELERY_FLIGHTS_QUEUE", "ingestion")
    CELERY_REPRESSOR_INGESTION_ENABLED = (
        os.getenv("CELERY_REPRESSOR_INGESTION_ENABLED", "1") == "1"
    )
    CELERY_REPRESSOR_QUEUE = os.getenv("CELERY_REPRESSOR_QUEUE", "ingestion")
    CELERY_POST_EXPIRATION_ENABLED = (
        os.getenv("CELERY_POST_EXPIRATION_ENABLED", "1") == "1"
    )
    CELERY_POST_EXPIRATION_INTERVAL_SECONDS = int(
        os.getenv("CELERY_POST_EXPIRATION_INTERVAL_SECONDS", "86400")
    )
    CELERY_POST_EXPIRATION_QUEUE = os.getenv("CELERY_POST_EXPIRATION_QUEUE", "ingestion")
    POST_EXPIRATION_DAYS = int(os.getenv("POST_EXPIRATION_DAYS", "7"))
    POST_EXPIRATION_CATEGORY_SLUGS = os.getenv(
        "POST_EXPIRATION_CATEGORY_SLUGS",
        "accion-represiva,accion-represiva-del-gobierno,movimiento-tropas,movimiento-militar",
    )
    AUTO_CONNECTIVITY_REPORTS_ENABLED = (
        os.getenv("AUTO_CONNECTIVITY_REPORTS_ENABLED", "1") == "1"
    )
    AUTO_CONNECTIVITY_REPORT_USER_EMAIL = os.getenv(
        "AUTO_CONNECTIVITY_REPORT_USER_EMAIL",
        "radar-bot@soscuba.local",
    )
